name: devfest2026_portal
description: "DevFest Live Quiz — attendee & admin portal"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.13.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  google_sign_in: ^7.1.1
  http: ^1.5.0
  socket_io_client: ^3.1.2
  qr_flutter: ^4.1.0
  file_picker: ^10.3.2
  google_fonts: ^8.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/devfest_login_illustration.png
